In [4]:
print('hello')

hello


In [11]:
import numpy as np
import pandas as pd
from numpy.linalg import norm, det, inv, eig
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy.linalg import lu, svd
from sklearn.preprocessing import StandardScaler

In [12]:
df=pd.read_csv('student_data_200-2.csv',index_col=0)
df
X = df.values
print(X)


[['Vihaan' 76 42 61 79]
 ['Anjali' 72 71 49 71]
 ['Vivaan' 81 91 53 43]
 ['Sneha' 53 88 85 60]
 ['Pooja' 76 48 96 36]
 ['Kunal' 57 61 52 71]
 ['Shaurya' 68 80 64 48]
 ['Nisha' 93 99 97 77]
 ['Riya' 72 57 96 67]
 ['Priya' 58 99 91 70]
 ['Arnav' 80 74 72 74]
 ['Priya' 58 40 73 42]
 ['Isha' 64 40 53 77]
 ['Atharv' 74 85 55 78]
 ['Reyansh' 79 52 63 97]
 ['Aditi' 94 60 78 45]
 ['Isha' 71 40 43 36]
 ['Shaurya' 53 99 79 53]
 ['Riya' 51 91 57 91]
 ['Ayaan' 75 57 46 92]
 ['Krishna' 58 40 71 76]
 ['Sneha' 60 66 86 94]
 ['Arnav' 48 47 69 72]
 ['Aditi' 76 44 96 50]
 ['Anjali' 59 66 35 46]
 ['Dhruv' 49 95 69 45]
 ['Riya' 97 91 69 95]
 ['Aarav' 100 79 63 48]
 ['Ayaan' 92 60 67 43]
 ['Sai' 35 93 79 100]
 ['Dhruv' 71 61 78 54]
 ['Priya' 82 35 49 73]
 ['Kunal' 61 35 61 40]
 ['Isha' 50 62 64 90]
 ['Atharv' 72 37 54 90]
 ['Aditya' 40 86 60 62]
 ['Arjun' 49 80 61 39]
 ['Rohan' 92 77 89 49]
 ['Arnav' 36 42 43 95]
 ['Neha' 62 39 68 52]
 ['Neha' 74 61 64 60]
 ['Kunal' 53 92 46 55]
 ['Kabir' 92 100 47 87]
 ['

In [ ]:

X_numeric = df.select_dtypes(include=[np.number])

X = X_numeric.values

v1 = X[0]

norm_1 = norm(v1, 1)   # L1 norm
norm_2 = norm(v1, 2)   # L2 norm

print("v1 =", v1)
print("L1 norm =", norm_1)
print("L2 norm =", norm_2)


              name  gujrati  maths  sci  english
student_id                                      
S001        Vihaan       76     42   61       79
S002        Anjali       72     71   49       71
S003        Vivaan       81     91   53       43
S004         Sneha       53     88   85       60
S005         Pooja       76     48   96       36
v1 = [76 42 61 79]
L1 norm = 258.0
L2 norm = 132.29512462672236


In [ ]:
X = df.select_dtypes(include=[np.number]).values

v1 = X[0]
v2 = X[1]

dot_product = np.dot(v1, v2)

angle = np.arccos(
    dot_product / (norm(v1) * norm(v2))
) * (180 / np.pi)

print("Dot product:", dot_product)
print("Angle (degrees):", angle)


Dot product: 17052
Angle (degrees): 14.13375569599555


In [21]:
A = X[:5]
B = X[5:10]

matrix_addition = A + B
matrix_multiplication = np.dot(A, B.T)
matrix_addition, matrix_multiplication

(array([[133, 103, 113, 150],
        [140, 151, 113, 119],
        [174, 190, 150, 120],
        [125, 145, 181, 127],
        [134, 147, 187, 106]]),
 array([[15675, 16224, 23226, 19015, 19647],
        [16024, 17120, 23945, 18692, 20634],
        [15977, 18244, 24994, 18988, 21540],
        [17069, 18964, 26506, 21012, 23721],
        [14808, 16880, 23904, 19836, 20416]]))

In [23]:
cov_matrix = np.cov(X.T)
eigenvalues, eigenvectors = eig(cov_matrix)

eigenvalues, eigenvectors

(array([412.98647709, 316.66453764, 333.27583506, 350.76174318]),
 array([[ 0.48204761, -0.07500015, -0.87165901,  0.04707081],
        [-0.75539265, -0.14050602, -0.3777597 ,  0.51666005],
        [ 0.43835897, -0.30867994,  0.31135261,  0.78461306],
        [-0.06966675, -0.93773649,  0.02382733, -0.33945408]]))

In [24]:
U_svd, S_svd, Vt_svd = svd(X)
U_svd, S_svd, Vt_svd

(array([[-6.69041562e-02, -7.02846949e-02,  7.74459064e-02, ...,
         -5.31100328e-02, -2.58471312e-02, -5.97489300e-02],
        [-6.82523307e-02,  3.02050624e-02,  6.45975927e-02, ...,
          8.47144165e-03, -8.06618215e-02, -4.18507152e-02],
        [-6.97014865e-02,  5.64028174e-02, -7.23769059e-03, ...,
          1.20404052e-02,  2.63210830e-02,  1.88218345e-02],
        ...,
        [-4.75041915e-02, -2.63103781e-02,  8.62539003e-03, ...,
          9.97149142e-01,  1.61096418e-04, -2.04653966e-03],
        [-5.98305666e-02,  4.61708282e-02, -1.11612276e-01, ...,
         -1.12002241e-03,  9.81353837e-01, -1.34501265e-02],
        [-7.66734537e-02,  7.86666798e-03, -6.81866465e-02, ...,
         -2.95135283e-03, -1.27831290e-02,  9.88958466e-01]],
       shape=(200, 200)),
 array([1925.7690313 ,  286.61251928,  261.6588413 ,  255.31853173]),
 array([[-0.50205899, -0.50265133, -0.5026633 , -0.49255255],
        [-0.45800765,  0.78381989, -0.41046907,  0.08585172],
        [ 

In [25]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
X_pca

array([[-0.71101356,  1.24482325],
       [ 0.53487991,  0.49044926],
       [ 0.44402871, -1.18693461],
       [ 0.51442135, -1.08727379],
       [-1.96756256, -1.48865473],
       [ 0.61978946,  0.45477662],
       [ 0.26567531, -1.05895637],
       [-0.56106087, -0.1902839 ],
       [-1.24300653, -0.16954495],
       [ 0.62652212, -0.82292352],
       [-0.23697835,  0.32737071],
       [-0.93746087, -0.90747579],
       [-0.19327772,  1.17111745],
       [ 0.79887685,  0.52370876],
       [-0.36941975,  1.95632151],
       [-1.57079375, -0.78919283],
       [-0.56802417, -0.60987085],
       [ 0.93795559, -1.52933141],
       [ 1.78005542,  0.77703576],
       [ 0.32824351,  1.83712592],
       [-0.52010001,  0.78691678],
       [-0.03103348,  1.01695426],
       [ 0.01596111,  0.39200161],
       [-1.93876331, -0.73443932],
       [ 0.9173161 , -0.57832245],
       [ 1.13781172, -1.74544002],
       [ 0.0488184 ,  1.29221451],
       [-0.73663371, -0.67929451],
       [-1.22168751,